spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dart

mongock:
  # runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package: "ru.otus.home8.mongock"
