DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255), LAST_NAME VARCHAR(255));
CREATE TABLE GENRE(ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255));
CREATE TABLE BOOK(ID BIGINT AUTO_INCREMENT PRIMARY KEY, NAME VARCHAR(255), AUTHOR_ID BIGINT REFERENCES AUTHOR(ID), GENRE_ID BIGINT REFERENCES GENRE(ID));
